"""Lua code builders and response parsers for Civ 6 game state.

Each domain has:
- build_*_query() -> str: returns Lua code to execute via FireTuner
- parse_*_response() -> dataclass: parses pipe-delimited output lines

All queries use print() for output (not return) and terminate with ---END---.
Output format: pipe-delimited fields, one entity per line.

This package re-exports all public symbols so that::

    from civ_mcp import lua as lq
    lq.build_units_query()
    lq.UnitInfo(...)

works identically to the old monolithic ``lua_queries`` module.
"""

# Re-export helpers & sentinel
from civ_mcp.lua._helpers import SENTINEL  # noqa: F401
from civ_mcp.lua.espionage import (  # noqa: F401
    build_get_spies_query,
    build_spy_escape_route,
    build_spy_mission,
    build_spy_travel,
    parse_spies_response,
)
from civ_mcp.lua.cities import (  # noqa: F401
    build_cities_query,
    build_city_attack,
    build_city_production_query,
    build_city_yield_focus_query,
    build_loyalty_query,
    build_produce_item,
    build_purchase_item,
    build_resolve_city_capture,
    build_set_yield_focus,
    build_verify_production,
    parse_cities_response,
    parse_city_production_response,
    parse_loyalty_response,
)
from civ_mcp.lua.diplomacy import (  # noqa: F401
    build_check_diplomacy_session_state,
    build_clear_blocking_diplomacy,
    build_close_orphan_sessions,
    build_check_war_state,
    build_deal_options_query,
    build_diplomacy_choices_query,
    build_diplomacy_query,
    build_diplomacy_respond,
    build_diplomacy_session_query,
    build_form_alliance,
    build_gossip_query,
    build_pending_deals_query,
    build_propose_peace,
    build_propose_trade,
    build_respond_to_deal,
    build_test_trade,
    build_send_diplo_action,
    build_war_close_session,
    build_war_dismiss_view,
    parse_deal_options_response,
    parse_gossip_response,
    parse_test_trade_response,
    parse_diplomacy_response,
    parse_diplomacy_sessions,
    parse_pending_deals_response,
)
from civ_mcp.lua.climate import (  # noqa: F401
    build_climate_query,
    parse_climate_response,
)
from civ_mcp.lua.congress import (  # noqa: F401
    build_congress_submit,
    build_congress_vote,
    build_register_wc_voter,
    build_world_congress_query,
    parse_world_congress_response,
)
from civ_mcp.lua.economy import (  # noqa: F401
    build_make_trade_route,
    build_teleport_to_city,
    build_trade_capacity_check,
    build_trade_destinations_query,
    build_trade_routes_query,
    parse_trade_destinations_response,
    parse_trade_routes_response,
)
from civ_mcp.lua.great_people import (  # noqa: F401
    build_activate_great_person,
    build_gp_advisor_query,
    build_great_people_query,
    build_patronize_great_person,
    build_recruit_great_person,
    build_reject_great_person,
    parse_gp_advisor_response,
    parse_great_people_response,
)
from civ_mcp.lua.governance import (  # noqa: F401
    build_appoint_governor,
    build_assign_governor,
    build_available_governments_query,
    build_change_government,
    build_choose_dedication,
    build_city_states_query,
    build_dedications_query,
    build_governors_query,
    build_policies_query,
    build_promote_governor,
    build_promote_unit,
    build_send_envoy,
    build_set_policies,
    build_unit_promotions_query,
    build_unit_upgrade_query,
    build_upgrade_unit,
    parse_city_states_response,
    parse_dedications_response,
    parse_governors_response,
    parse_policies_response,
    parse_unit_promotions_response,
)
from civ_mcp.lua.map import (  # noqa: F401
    build_district_advisor_query,
    build_empire_resources_query,
    build_found_city,
    build_global_settle_scan,
    build_map_area_query,
    build_ownership_delta,
    build_purchasable_tiles_query,
    build_purchase_tile,
    build_revealed_tiles_seed_query,
    build_settle_advisor_query,
    build_static_map_dump,
    build_stockpile_query,
    build_strategic_map_query,
    build_verify_city_at,
    build_wonder_advisor_query,
    parse_district_advisor_response,
    parse_empire_resources_response,
    parse_map_response,
    parse_ownership_delta,
    parse_purchasable_tiles_response,
    parse_revealed_tiles_seed,
    parse_settle_advisor_response,
    parse_static_map_dump,
    parse_stockpile_response,
    parse_strategic_map_response,
    parse_verify_city_at,
    parse_wonder_advisor_response,
)

# Re-export all models
from civ_mcp.lua.models import (  # noqa: F401
    AgendaInfo,
    AppointedGovernor,
    AgentExtras,
    BuilderInfo,
    BuilderTask,
    CityLoyalty,
    CityRow,
    ClimateStatus,
    DiarySnapshot,
    BeliefInfo,
    CityInfo,
    CityReligionInfo,
    CitySnapshot,
    CityStateInfo,
    CivicOption,
    CivInfo,
    CombatEstimate,
    CongressProposal,
    CongressResolution,
    DealItem,
    DealOptions,
    DedicationChoice,
    DedicationStatus,
    DemographicEntry,
    DiplomacyChoice,
    DiplomacyModifier,
    DiplomacySession,
    DisasterEvent,
    DistrictPlacement,
    EnvoyStatus,
    FogBoundary,
    GameNotification,
    GameOverStatus,
    GameOverview,
    GovernmentStatus,
    GovernorInfo,
    GovernorPromotion,
    GovernorStatus,
    GossipEntry,
    GPAdvisorCity,
    GPAdvisorResult,
    GreatPersonInfo,
    GrievanceRow,
    LockedCivic,
    LockedTech,
    NearbyResource,
    OwnershipDelta,
    OwnedResource,
    PantheonStatus,
    PathingEstimate,
    PendingDeal,
    PlayerRow,
    PolicyInfo,
    PolicySlot,
    ProductionOption,
    PromotionOption,
    PurchasableTile,
    ReligionBeliefOption,
    ReligionFoundingStatus,
    ReligionInfo,
    ReligionStatus,
    ReligionSummary,
    ResourceStockpile,
    RivalSnapshot,
    ScoreEntry,
    SettleCandidate,
    SpyInfo,
    StaticMapDump,
    StaticMapTile,
    StrategicMapData,
    TechCivicStatus,
    TechOption,
    TestTradeItem,
    TestTradeResult,
    ThreatInfo,
    TileInfo,
    TradeableCity,
    TradeDestination,
    TraderInfo,
    TradeRouteStatus,
    TurnEvent,
    TurnSnapshot,
    UnclaimedResource,
    UnitInfo,
    UnitPromotionStatus,
    UnitUpgradeInfo,
    SpaceProject,
    VictoryPlayerProgress,
    VictoryProgress,
    VisibleCity,
    WorldCongressStatus,
    WonderPlacement,
)
from civ_mcp.lua.notifications import (  # noqa: F401
    BLOCKING_TOOL_MAP,
    NOTIFICATION_TOOL_MAP,
    build_end_turn,
    build_end_turn_blocking_query,
    build_notifications_query,
    parse_end_turn_blocking,
    parse_notifications_response,
)

# --- Domain module re-exports ---
from civ_mcp.lua.overview import (  # noqa: F401
    build_diary_full_query,
    build_gameover_check,
    build_overview_query,
    build_rival_snapshot_query,
    parse_diary_full_response,
    parse_gameover_response,
    parse_overview_response,
    parse_rival_snapshot_response,
)
from civ_mcp.lua.religion import (  # noqa: F401
    build_choose_pantheon,
    build_found_religion,
    build_pantheon_status_query,
    build_religion_beliefs_query,
    build_religion_status_query,
    build_spread_religion,
    parse_pantheon_status_response,
    parse_religion_beliefs_response,
    parse_religion_status_response,
)
from civ_mcp.lua.tech import (  # noqa: F401
    build_set_civic,
    build_set_civic_gamecore,
    build_set_research,
    build_set_research_gamecore,
    build_tech_civics_query,
    parse_tech_civics_response,
)
from civ_mcp.lua.units import (  # noqa: F401
    build_alert_unit,
    build_attack_followup_query,
    build_attack_unit,
    build_automate_explore,
    build_builder_tasks_query,
    build_combat_estimate_query,
    build_delete_unit,
    build_fortify_remaining_units,
    build_fortify_unit,
    build_heal_unit,
    build_build_route,
    build_improve_tile,
    build_pathing_estimate_query,
    build_post_move_visibility_query,
    build_remove_feature,
    build_remove_improvement,
    build_repair_improvement,
    build_sacrifice_builder_charges,
    build_move_unit,
    build_skip_remaining_units,
    build_skip_unit,
    build_sleep_unit,
    build_fog_neighbor_query,
    build_threat_scan_query,
    build_unit_position_query,
    build_units_query,
    diff_threats,
    parse_blocked_diagnostic,
    parse_builder_tasks,
    parse_combat_estimate,
    parse_fog_neighbor_response,
    parse_pathing_estimate,
    parse_post_move_visibility,
    parse_threat_scan_response,
    parse_units_response,
)
from civ_mcp.lua.victory import (  # noqa: F401
    build_victory_progress_query,
    build_victory_proximity_query,
    parse_victory_progress_response,
)
